# Generated by Django 4.2.1 on 2023-05-07 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cuenta", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cuenta",
            old_name="is_seller",
            new_name="is_staff",
        ),
    ]
