# Generated by Django 4.2.1 on 2023-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cuenta", "0002_rename_is_seller_cuenta_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta",
            name="telefono",
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
