# Generated by Django 4.2.1 on 2023-05-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cuenta", "0003_cuenta_telefono"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuenta",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
