# Generated by Django 4.2.1 on 2023-05-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("imagen", models.ImageField(blank=True, upload_to="photos/categoria")),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
    ]
