# Generated by Django 4.2.1 on 2023-05-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("almacen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
