# Generated by Django 4.2.1 on 2023-05-11 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("almacen", "0003_variacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variacion",
            options={"verbose_name": "Variación", "verbose_name_plural": "Variaciones"},
        ),
    ]
