# Generated by Django 4.2.1 on 2023-05-12 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("almacen", "0005_rename_variacion_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variation",
            old_name="producto",
            new_name="product",
        ),
    ]
